"""make level description mandatory

Revision ID: 951c848a9667
Revises: 599f2969c22e
Create Date: 2024-04-28 23:34:02.126531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951c848a9667'
down_revision: Union[str, None] = '599f2969c22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'description')
    # ### end Alembic commands ###
